turbine_type: "floating"
# Primary model configurations
orbit_config: base_floating_deep_install.yaml
wombat_config: base_floating_deep_operations.yaml
floris_config: base_floating_deep_floris_jensen.yaml
weather_profile: era5_41.0N_125.0W_1989_2019.csv

# Shared input connections
orbit_start_date: 1/1/1998
orbit_weather_cols:
- windspeed_100m
- windspeed_10m
- waveheight
floris_wind_direction: wind_direction_100m
floris_windspeed: windspeed_145m
floris_x_col: floris_x
floris_y_col: floris_y

# Create the necessary connections
# NOTE: these are default values, but worth highlighting for an example
connect_floris_to_layout: true
conenct_orbit_array_design: true

# High-level project financials
fixed_charge_rate: 0.0648 # real FCR from national LCOE study, 25 year lifetime instead of 30
discount_rate: 0.025
loss_ratio: 0.1
offtake_price: 80

# Cash flow settings
project_capex_date:
- !!python/tuple
  - 1996
  - 1
- !!python/tuple
  - 1996
  - 7
- !!python/tuple
  - 1997
  - 1
- !!python/tuple
  - 1997
  - 7
soft_capex_date: !!python/tuple
- 1995
- 1
system_capex_date:
- !!python/tuple
  - 1996
  - 1
- !!python/tuple
  - 1996
  - 4
- !!python/tuple
  - 1996
  - 7
- !!python/tuple
  - 1996
  - 10
- !!python/tuple
  - 1997
  - 1
- !!python/tuple
  - 1997
  - 4
- !!python/tuple
  - 1997
  - 7
- !!python/tuple
  - 1997
  - 10
- !!python/tuple
  - 1998
  - 1
- !!python/tuple
  - 1998
  - 4
- !!python/tuple
  - 1998
  - 7
- !!python/tuple
  - 1998
  - 10
- !!python/tuple
  - 1999
  - 1
- !!python/tuple
  - 1999
  - 4
- !!python/tuple
  - 1999
  - 7
- !!python/tuple
  - 1999
  - 10
turbine_capex_date:
- !!python/tuple
  - 1996
  - 1
- !!python/tuple
  - 1996
  - 4
- !!python/tuple
  - 1996
  - 7
- !!python/tuple
  - 1996
  - 10
- !!python/tuple
  - 1997
  - 1
- !!python/tuple
  - 1997
  - 4
- !!python/tuple
  - 1997
  - 7
- !!python/tuple
  - 1997
  - 10
- !!python/tuple
  - 1998
  - 1
- !!python/tuple
  - 1998
  - 4
- !!python/tuple
  - 1998
  - 7
- !!python/tuple
  - 1998
  - 10
- !!python/tuple
  - 1999
  - 1
- !!python/tuple
  - 1999
  - 4
- !!python/tuple
  - 1999
  - 7
- !!python/tuple
  - 1999
  - 10
