num_turbines: 50
turbine_rating_MW: 12
enable_cost_and_scaling_modifications: False
construction_months: 9
hub_height_m: 80
rotor_diameter_m: 77
turbine_spacing_rotor_diameter: 4
row_spacing_rotor_diameter: 10
base_topping_breakpoint: 0.8
fuel_cost_usd_per_gal: 1.5
turbine_delivery_rate_per_week: 10
wind_shear: 0.2
foundation_depth_m: 2.36
rated_thrust_N: 589000
bearing_pressure_Pa: 191521
gust_velocity_50_year_m/s: 59.5
line_frequency: 60
combined_homerun_trench_length_km: 50
non_erection_wind_delay_critical_height_m: 10
non_erection_wind_delay_critical_wind_speed_m/s: 15
distance_to_interconnect_mi: 5
interconnect_voltage_kV: 130
new_switchyard: True
road_length_adder_m: 5000
road_quality: 0.6
percent_roads_to_be_constructed: 33
road_width_ft: 20.0
road_thickness_in: 8
calculate_road_cost_for_distributed_wind: False
site_prep_area_for_distributed_wind_m2: 0
crane_width_m: 12.2
num_highway_permits: 10
num_access_roads: 2
overtime_multiplier: 1.4
allow_same_flag: false
override_total_management_cost_for_distributed: 50
markup_contingency: 0.03
markup_warranty_management: 0.0002
markup_sales_and_use_tax: 0
markup_overhead: 0.05
markup_profit_margin: 0.05
utility_interconnection_fees_distributed_wind: 0
labor_cost_multiplier: 1
crane_breakdown_fraction: 0
data_tables: landbosse_test_landbosse_table.xlsx

component:
  nacelle:
    mass_t: 50
    surface_area_m2: 33
  hub:
    mass_t: 15.4
    surface_area_m2: 11.3
  blade:
    mass_t: 5.2
    surface_area_m2: 33.44
  tower_section:
    mass_t: [59.8, 39.3, 30.9]
    surface_area_m2: [95.89, 96.25, 90]
    height_m: [30, 30, 30]
