num_turbines: 50  # Number of turbines
turbine_rating_MW: 12  # Capacity of turbine (MW)
enable_cost_and_scaling_modifications: False  # Should cost and scaling modifications be applied (true/false)
construction_months: 9  # Total construction duration (months)
hub_height_m: 80  # Turbine hub height (m)
rotor_diameter_m: 77  # Turbine rotor diameter (m)
turbine_spacing_rotor_diameter: 4  # Layout spacing between turbines in each row, in rotor diameters
row_spacing_rotor_diameter: 10  # Layout spacing between rows, in rotor diameters
base_topping_breakpoint: 0.8  # Height at which cranes change from 'Base' to 'Topping', represented as a fraction of hub height
fuel_cost_usd_per_gal: 1.5  # Cost of fuel per gallon ($/gal)
turbine_delivery_rate_per_week: 10  # Number of turbine deliveries (all components) per week
wind_shear: 0.2  # Wind shear (assumed constant across all timestamps and turbines)
foundation_depth_m: 2.36  # Depth of concrete foundation (m)
rated_thrust_N: 589000  # Rated horizontal thrust of turbine (N)
bearing_pressure_Pa: 191521  # Bearing pressure capacity of soil underneath foundations (Pa)
gust_velocity_50_year_m/s: 59.5  # 50 year wind gust velocity (m/s)
line_frequency: 60  # Electrical frequency of grid (Hz
combined_homerun_trench_length_km: 50  # Combined homerun trench length to substation (km) (optional - can be null but cannot be omitted)
non_erection_wind_delay_critical_height_m: 10  # When calculating wind delays for non-erection tasks, shear values to this height (m)
non_erection_wind_delay_critical_wind_speed_m/s: 15  # When calculating wind delays for non-erection tasks, wind speeds above this value will force work to stop (m/s)
distance_to_interconnect_mi: 5  # Distance from substation to switchyard (miles)
interconnect_voltage_kV: 130  # Voltage of grid (kV)
new_switchyard: True  # Should a new switchyard be built (true/false)
road_length_adder_m: 5000  # Distance from site entry point to the project (m)
road_quality: 0.6  # Non-dimensional representation of the quality of roads. 0 is poor quality, 1 is good quality. A higher road quality reduces the total road cost
percent_roads_to_be_constructed: 33  # What percentage of roads need to be constructed vs already exist
road_width_ft: 20.0  # Width of roads (ft)
road_thickness_in: 8  # Thickness of roads (in)
calculate_road_cost_for_distributed_wind: False  # Should road costs be included in the calculation for distributed wind projects (true/false)
site_prep_area_for_distributed_wind_m2: 0  # Site prep area for distributed wind projects (m^2)
crane_width_m: 12.2  # Width of crane (m)
num_highway_permits: 10  # Number of highway permits required
num_access_roads: 2  # Number of site access roads required
overtime_multiplier: 1.4  # Labor cost multiplier for overtime work
allow_same_flag: false  # flag to indicate whether choosing same base and topping crane is allowed (true/false)
override_total_management_cost_for_distributed: 50  # For distributed wind project, override the calculated management cost and use this value instead
markup_contingency: 0.03  # Markup contingency
markup_warranty_management: 0.0002  # Markup warranty management
markup_sales_and_use_tax: 0  # Markup sales and use tax
markup_overhead: 0.05  # Markup overhead
markup_profit_margin: 0.05  # Markup profit margin
utility_interconnection_fees_distributed_wind: 0  # Fee for connecting to the grid (distributed wind projects only)
labor_cost_multiplier: 1  # Multiplier to modify labor costs
crane_breakdown_fraction: 0  # What fraction of cranes will breakdown. 0 means none, 1 means all. Breakdowns increase the total erection duration
data_tables: landbosse_test_landbosse_table.xlsx  # Path to excel spreadsheet containing other LandBOSSE inputs.

component:
  nacelle:
    mass_t: 50  # nacelle mass (t)
    surface_area_m2: 33  # nacelle surface area (m^2)
  hub:
    mass_t: 15.4  # hub mass (t)
    surface_area_m2: 11.3  # hub surface area (m^2)
  blade:
    mass_t: 5.2  # Blade mass (t) (one blade)
    surface_area_m2: 33.44  # Blade surface area (m^2) (one blade)
  tower_section:  # Each entry should be a list representing the different tower sections, from bottom to top. All lists must be the same length
    mass_t: [59.8, 39.3, 30.9]  # List of tower section masses (t)
    surface_area_m2: [95.89, 96.25, 90]  # List of tower section surface areas (m^2)
    height_m: [30, 30, 30]  # List of tower section heights (m)
