# floating moderate base case
site:
  depth: 200 # moderate site
  distance: 148 # moderate site
  distance_to_landfall: 83 # moderate site
  mean_windspeed: 8.41  # avg from weather profile in the Humboldt site
plant:
  layout: grid
  num_turbines: 67
  row_spacing: 6.63 
  substation_distance: 1
  turbine_spacing: 7.09 
landfall:
  interconnection_distance: 4 # moderate site
  trench_length: 6  # COE Review 2022
turbine: 15MW_generic
oss_design:
  num_substations: 1
port:
  monthly_rate: 2569631.41631766
  sub_assembly_lines: 1
  turbine_assembly_cranes: 1
  num_cranes : 1
  sub_storage: 5

# Vessels
array_cable_install_vessel: demand_adjusted_cable_lay_vessel
export_cable_install_vessel: demand_adjusted_cable_lay_vessel
mooring_install_vessel: demand_adjusted_support_vessel
oss_install_vessel: demand_adjusted_floating_heavy_lift_vessel
support_vessel: demand_adjusted_support_vessel
towing_vessel: demand_adjusted_towing_vessel
ahts_vessel: demand_adjusted_support_vessel
towing_vessel_groups:
  num_groups : 1 # note these numbers are different than the default for ORBIT- I believe ORCA assumes only one installation group of 3 vessels total for floating
  station_keeping_vessels: 1
  towing_vessels: 2

# Module Specific
substructure:
  takt_time: 336
  ahts_vessel: demand_adjusted_support_vessel
OffshoreSubstationInstallation:
  feeder: demand_adjusted_floating_barge
array_system_design:
  free_cable_length: 0.5
  floating_cable_depth: 200
  cables:
  - _XLPE_630mm_66kV
  location_data: base_floating_moderate_layout
export_system_design:
  cables: XLPE_1000m_220kV
  percent_added_length: 0.0
mooring_system_design:
  anchor_type: Suction Pile
mooring_system:
  num_lines: 3 #int
  line_mass: 268 #t
  line_cost: 651025 #USD
  anchor_mass: 10 #t
  anchor_cost: 58487  #USD
  anchor_type: Suction Pile 

# Configured Phases
design_phases:
- CustomArraySystemDesign
- ElectricalDesign
- MooringSystemDesign
- SemiSubmersibleDesign
install_phases:
  ArrayCableInstallation: 0
  ExportCableInstallation: 0
  MooredSubInstallation: 0
  MooringSystemInstallation: 0
  OffshoreSubstationInstallation: 0

project_parameters:
  turbine_capex: 1770  # new assumed turbine price COE Review 2023

