name: base_floating_moderate
weather: gulf_of_maine_43.5_-69.0.csv
service_equipment:
  - [ctv.yaml, 3]
  - [dsv.yaml, 2]
  - ahv.yaml
layout: base_floating_moderate_layout.csv
inflation_rate: 0
fixed_costs: fixed_costs_FAD.yaml
workday_start: 6
workday_end: 22
start_year: 2000
end_year: 2019
project_capacity: 1980
port_distance: 148
port: port_148km.yaml
