# floating base case
site:
  depth: 739 # COE Review 2021
  distance: 189 # COE Review 2021
  distance_to_landfall: 36 # COE Review 2021
  mean_windspeed: 8.41  # avg from weather profile in the Humboldt site
plant:
  layout: custom
  num_turbines: 50
  row_spacing: 7 
  turbine_spacing: 7 
turbine: 12MW_generic
oss_design:
  num_substations: 1
port:
  sub_assembly_lines: 3
  turbine_assembly_cranes: 3
  num_cranes : 3

# Vessels
array_cable_install_vessel: demand_adjusted_cable_lay_vessel
export_cable_install_vessel: demand_adjusted_cable_lay_vessel
mooring_install_vessel: demand_adjusted_support_vessel
oss_install_vessel: demand_adjusted_floating_heavy_lift_vessel
ahts_vessel: demand_adjusted_support_vessel
ahts_vessel: example_ahts_vessel
towing_vessel: demand_adjusted_towing_vessel
towing_vessel_groups:
  num_groups : 1 # note these numbers are different than the default for ORBIT- I believe ORCA assumes only one installation group of 3 vessels total for floating
  ahts_vessels: 1
  towing_vessels: 2

# Module Specific
substructure:
  takt_time: 168
OffshoreSubstationInstallation:
  feeder: demand_adjusted_floating_barge
array_system_design:
  free_cable_length: 0.5
  floating_cable_depth: 200
  cables:
  - XLPE_630mm_66kV
  location_data: base_floating_2024_layout
export_system_design:
  cables: XLPE_1000mm_220kV
  percent_added_length: 0.0
  landfall:
    interconnection_distance: 8 # COE Review 2021
    trench_length: 6  # COE Review 2021
# Configured Phases
design_phases:
- CustomArraySystemDesign
- ElectricalDesign
- MooringSystemDesign
- SemiSubmersibleDesign
install_phases:
  ArrayCableInstallation: 0
  ExportCableInstallation: 0
  MooredSubInstallation: 0
  MooringSystemInstallation: 0
  OffshoreSubstationInstallation: 0

project_parameters:
  turbine_capex: 1770  # COWER: 2024 Edition; Turbine CapEx
  #supply_chain_capex: 756 # 439 $/kW for investments and 317 $/kW for vessels # commented out given DOE's comments about leaving this out for comparability with other technologies