# Fixed bottom base case
site:
  depth: 34  # COE Review 2021
  distance: 116  # COE Review 2021
  distance_to_landfall: 50  # COE Review 2021
  mean_windspeed: 9.17   # avg from weather profile in the Vineyard Wind 1 site
plant:
  layout: grid
  num_turbines: 50
  row_spacing: 7  # COE Review 2021
  substation_distance: 1
  turbine_spacing: 7  # COE Review 2021
landfall:
  interconnection_distance: 9  # COE Review 2021
  trench_length: 7   # COE Review 2021
turbine: 12MW_generic
port:
  monthly_rate: 2000000.0 # COE Review 2021
  sub_assembly_lines: 1  # COE Review 2021
  turbine_assembly_cranes: 1  # COE Review 2021
# Vessels
array_cable_install_vessel: example_cable_lay_vessel
export_cable_bury_vessel: example_cable_lay_vessel
export_cable_install_vessel: example_cable_lay_vessel
spi_vessel: example_scour_protection_vessel
oss_install_vessel: example_heavy_lift_vessel
wtiv: example_wtiv

# Module Specific
MonopileDesign:
  monopile_steel_cost: 2250 # COE Review 2021
  tp_steel_cost: 3230 # COE Review 2021
scour_protection_design:
  cost_per_tonne: 40  # COE Review 2021
  scour_protection_depth: 1  # COE Review 2021
oss_design:
  num_substations: 1
array_system_design:
  cables:
  - XLPE_630mm_66kV
  location_data: COE_2022_fixed_bottom_layout_base
export_system_design:
  cables: XLPE_1000m_220kV
  percent_added_length: 0.0
OffshoreSubstationInstallation:
  feeder: example_heavy_feeder
  num_feeders: 1
# Configured Phases
design_phases:
- CustomArraySystemDesign
- ExportSystemDesign
- MonopileDesign
- ScourProtectionDesign
- OffshoreSubstationDesign
install_phases:
  ArrayCableInstallation: 0
  ExportCableInstallation: 0
  MonopileInstallation: !!python/tuple
  - ScourProtectionInstallation
  - 0.5
  OffshoreSubstationInstallation: 0
  ScourProtectionInstallation: 0
  TurbineInstallation: !!python/tuple
  - MonopileInstallation
  - 0.1

project_parameters:
  turbine_capex: 1500 # new assumed turbine price COE Review 2022
  commissioning: 0.01
  decommissioning: 0.15
