name: COE_2022_floating
library: library
#weather: UMaine.csv
weather: era5_41.0N_125.0W_1989_2019.csv
service_equipment:
  - ctv1.yaml
  - ctv2.yaml
  - ctv3.yaml
  - clv.yaml
  - jackup.yaml
  - dsv.yaml
layout: COE_2022_floating_layout_base.csv
inflation_rate: 0
fixed_costs: COE_2022_floating_fixed_costs.yaml
workday_start: 7
workday_end: 19
start_year: 1999
end_year: 2019
project_capacity: 600
port_distance: 139
