name: COE_2022_fixed_bottom
library: library
#weather: UMaine.csv
weather: era5_40.0N_72.5W_1990_2020.csv
service_equipment:
  - ctv1.yaml
  - ctv2.yaml
  - ctv3.yaml
  - clv.yaml
  - jackup.yaml
  - dsv.yaml
layout: COE_2022_fixed_bottom_layout_base.csv
inflation_rate: 0
fixed_costs: COE_2022_fixed_bottom_fixed_costs.yaml
workday_start: 7
workday_end: 19
start_year: 2000
end_year: 2020
project_capacity: 600
port_distance: 116
